[package]
name = "proc"
version = "0.0.0"
authors = ["Julian Orth <ju.orth@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
libc = "0.2"
quote = "1"
proc-macro2 = "1"
syn = "1"
regex = "1"
lazy_static = "1"
