name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  glibc-2.23:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        uname -a
        ldd --version
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        echo "::add-path::$HOME/.cargo/bin"
    - name: Build
      run: sudo -E cargo build --verbose
    - name: Run tests
      run: sudo -E $HOME/.cargo/bin/cargo test --verbose
