name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    - name: Build
      run: sudo -E cargo build --verbose
    - name: Run tests
      run: sudo -E cargo test --verbose
