name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  glibc-2_31:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Show env
      run: |
        uname -a
        ldd --version
    - name: Install
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Build
      run: sudo -E $HOME/.cargo/bin/cargo build --verbose
    - name: Run tests
      run: sudo -E $HOME/.cargo/bin/cargo test --verbose
  latest-glibc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show env
        run: |
          uname -a
          ldd --version
      - name: Install
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Build
        run: sudo -E $HOME/.cargo/bin/cargo build --verbose
      - name: Run tests
        run: sudo -E $HOME/.cargo/bin/cargo test --verbose
  latest-musl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show env
        run: |
          uname -a
          ldd --version
      - name: Install
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          . $HOME/.cargo/env
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get install musl musl-tools
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          export RUST_BACKTRACE=1
          sudo -E $HOME/.cargo/bin/cargo build --verbose --target x86_64-unknown-linux-musl
      - name: Run tests
        run: sudo -E $HOME/.cargo/bin/cargo test --verbose --target x86_64-unknown-linux-musl
