name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        . $HOME/.cargo/env
        CB=$HOME/.cargo/bin
    - name: Build
      run: |
        sudo -E $CB/cargo build --verbose
    - name: Run tests
      run: |
        sudo -E $CB/cargo test --verbose
